### ISSUE TITLE
Building from scratch fails

### ISSUE THREAD

**Issue by rgpinel** [inria-paris-robotic-lab/prl_ur5_robot#1]
Hi,

When running `rosdep install --from-paths src --ignore-src --skip-keys=python-pymodbus -r -y`, it fails with:

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ur_robot_driver: Cannot locate rosdep definition for [ur_msgs]
onrobot_control: Cannot locate rosdep definition for [ur_msgs]
```
This is because [https://github.com/fmauch/universal_robot/tree/calibration_devel](url) deleted ur_msgs package among many other things: [https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/384](url)

We need to bind universal_robot package to commit: [https://github.com/fmauch/universal_robot/commit/90c141b4719dd0df87baef12c46c26c374608ba1](url) and Universal_Robots_ROS_Driver to commit: [https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/commit/b5e8c56f07eba0df40e8149cf058c9d9efebfde5](url)

**Comment by ikalevatykh** [comment]
Check if https://github.com/inria-paris-robotic-lab/prl_ur5_robot/commit/ddf6171fdc1622c0ed5f756b55daa05d51f389c5 helps
